site_name: SparkCodeInternal
repo_name: "hwanghw/SparkCodeInternal"
repo_url: "https://github.com/hwanghw/SparkCodeInternal"
edit_uri: "/hwanghw/SparkCodeInternal/tree/main/docs"
docs_dir: "docs"
theme: 
  name: mkdocs
  navigation_depth: 2

nav:
  - Introduction: 'index.md'
  - Spark Core:
    - YarnAllocator: 'SparkCore/YarnAllocator.md'
    - ShuffleService: 'SparkCore/ShuffleService.md'
  - Spark SQL:
      - AQE: 'SparkSQL/AQE.md'
markdown_extensions:
    - toc:
        permalink: true
    - smarty
    - sane_lists
    - admonition
    - fenced_code
    - attr_list
    - md_in_html