site_name: SparkCodeInternal
repo_name: "hwanghw/SparkCodeInternal"
repo_url: "https://github.com/hwanghw/SparkCodeInternal"
edit_uri: "/hwanghw/SparkCodeInternal/tree/main/docs"
docs_dir: "docs"
theme: 
  name: mkdocs
  navigation_depth: 2

nav:
  - Introduction: 'index.md'
  - Spark Core:
      - TaskScheduling: "SparkCore/TaskScheduling.md"
      - YarnAllocator: 'SparkCore/YarnAllocator.md'
      - ShuffleService: 'SparkCore/ShuffleService.md'
  - Spark SQL:
      - Analyzer: 'SparkSQL/Analyzer.md'
      - SparkPlan: 'SparkSQL/SparkPlan.md'
      - AQE: 'SparkSQL/AQE.md'
      - Aggregation: 'SparkSQL/Aggregation.md'
      - Join: 'SparkSQL/Join.md'
      - Pivot: 'SparkSQL/Pivot.md'
      - Hive: 'SparkSQL/Hive.md'
  - Spark Structured Streaming:
      - MicroBatchExecution: 'SparkStructuredStreaming/MicroBatchExecution.md'
      - RocksDBFileManager: 'SparkStructuredStreaming/RocksDBFileManager.md'
      - KafkaSqlConnector: 'SparkStructuredStreaming/KafkaSqlConnector.md'
markdown_extensions:
    - toc:
        permalink: true
    - smarty
    - sane_lists
    - admonition
    - fenced_code
    - attr_list
    - md_in_html